# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 4088
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 3.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# speed smoother - limits acceleration and smooths anything above limit
max_acceleration: 2.0 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
# NOTE: max real angle ~.34 rad
steering_angle_to_servo_gain: -1.15
steering_angle_to_servo_offset: 0.51

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm
wheelbase: .25

vesc_driver:
  port: /dev/vesc
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 20.0
  brake_min: -20000.0
  brake_max: 100000.0
  speed_min: -1000
  speed_max: 1000 # ~.25m/s
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.1
  servo_max: 0.9
